#!/usr/bin/perl
# POD {{{
=head1 NAME

xthrow - Throw X windows around the screen

=head1 SYNOPSIS

	xthrow <command>

=over
	
=item B<Command specific syntax:>

	xthrow mv-[left|right]
	xthrow mv-[top|bottom]-[left|right]
	xthrow mv-[center|top|right|bottom|left]
	xthrow debug

=back

=head1 COMMANDS

=over 8

=item B<mv-left, mv-right>

Move the active window to occupy the entire left or right side of the screen.
The window will be resized to occupy half the screen width.

=item B<mc-center, mv-top, mv-bottom, mv-top-left, mv-top-right, mv-bottom-left, mv-bottom-right>

Move the active window to the center, center top, center bottom, top left, top right, bottom left or bottom right of the screen.
Unlike mv-left or mv-right this does not resize the window.

=item B<debug>

Display various debugging information about the active window and the screen.

=back

=head1 INSTALLATION

XThrow requires a few external modules before it can work correctly. Follow the following stages to get everything working.

	sudo apt-get install wmctrl

... or whatever package manager your system supports.

=head1 BUGS

Quite probably.

Please report to https://github.com/hash-bang/XThrow when found.

=head1 AUTHOR

Matt Carter <m@ttcarter.com>

=cut
# }}} POD

package xthrow;
use Switch;
use constant {
	DISPLAY => ':0.0',
	DESKTOP_NAME => 'Desktop', # Match the desktop window by this string
	OFFSET_LEFT => 3,
	OFFSET_TOP => 2,
	OFFSET_RIGHT => 2,
	OFFSET_BOTTOM => 2,
};
use Data::Dumper;
our $VERSION = '0.1.0';

$cmd = shift;

# Slurp the actively focused window ID from xprop
my $xprop = "xprop -display " . DISPLAY . " -root";
($winid) = (`$xprop` =~ /_NET_ACTIVE_WINDOW.*? # ([0-9a-fx]+)/s);

my ($wx, $wy, $wwidth, $wheight); # Window x,y,width,height
my ($sx, $sy, $swidth, $sheight); # Desktop x,y,width,height

$info = `wmctrl -G -l`; # Scrape wmctrl for window info
for (split /\n/, $info) {
	my @bits = split /\s+/;
	if (hex($bits[0]) == hex($winid)) {
		($junk,$junk,$wx,$wy,$wwidth,$wheight) = @bits;
	} elsif ($bits[7] eq DESKTOP_NAME) {
		($junk,$junk,$sx,$sy,$swidth,$sheight) = @bits;
	}
}

switch($cmd) {
	case 'debug' {
		print "Win ID: $winid\n";
		print "Screen Pos: $sx, $sy / $swidth x $sheight\n";
		print "Window Pos: $wx, $wy / $wwidth x $wheight\n";
	}
	case 'mv-top-left' {
		$run = "wmctrl -i -r $winid -e 0," . OFFSET_LEFT . "," . OFFSET_TOP . ",$wwidth,$wheight";
	}
	case 'mv-top-right' {
		$run = "wmctrl -i -r $winid -e 0," . ($swidth - $wwidth - OFFSET_RIGHT) . "," . OFFSET_TOP . ",$wwidth,$wheight";
	}
	case 'mv-bottom-left' {
		$run = "wmctrl -i -r $winid -e 0," . OFFSET_LEFT . "," . ($sheight - $wheight - OFFSET_BOTTOM) . ",$wwidth,$wheight";
	}
	case 'mv-bottom-right' {
		$run = "wmctrl -i -r $winid -e 0," . ($swidth - $wwidth - OFFSET_RIGHT) . "," . ($sheight - $wheight - OFFSET_BOTTOM) . ",$wwidth,$wheight";
	}
	case 'mv-center' {
		$run = "wmctrl -i -r $winid -e 0," . (($swidth - $wwidth) /2) . "," . (($sheight - $wheight) /2) . ",$wwidth,$wheight";
	}
	case 'mv-top' {
		$run = "wmctrl -i -r $winid -e 0," . (($swidth - $wwidth) /2) . "," . OFFSET_TOP . ",$wwidth,$wheight";
	}
	case 'mv-left' {
		$run = "wmctrl -i -r $winid -e 0," . OFFSET_LEFT . "," . OFFSET_TOP . "," . ($swidth/2) . "," . ($sheight - OFFSET_BOTTOM - OFFSET_TOP);
	}
	case 'mv-bottom' {
		$run = "wmctrl -i -r $winid -e 0," . (($swidth - $wwidth) /2) . "," . ($sheight - $wheight - OFFSET_BOTTOM) . ",$wwidth,$wheight";
	}
	case 'mv-right' {
		$run = "wmctrl -i -r $winid -e 0," . ($swidth - $wwidth - OFFSET_RIGHT) . "," . OFFSET_TOP . "," . ($swidth/2) . "," . ($sheight - OFFSET_BOTTOM - OFFSET_TOP);
	}
	else {
		print "Unknown command: $cmd\n";
	}
}

if ($run) { # Run something
	$run = "DISPLAY=" . DISPLAY . " $run";
	print "RUN [$run]";
	exec($run);
}
